/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package org.apache.oodt.cas.catalog.query.parser;

public interface QueryParserConstants {

  int EOF = 0;
  int AND = 5;
  int OR = 6;
  int QUOTE = 7;
  int EQUALS = 8;
  int SEMI_COLON = 9;
  int COMMA = 10;
  int OPEN_BRACES = 11;
  int CLOSE_BRACES = 12;
  int OPEN_PARENS = 13;
  int CLOSE_PARENS = 14;
  int BUCKET_NAME_KEY = 15;
  int CUSTOM_NAME_KEY = 16;
  int P_KEY = 17;
  int STRING_LITERAL = 18;
  int TERM = 19;
  int NON_TERM = 20;
  int EQ = 21;
  int GE = 22;
  int GT = 23;
  int LE = 24;
  int LT = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"AND\"",
    "\"OR\"",
    "\"\\\'\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"bucketNames\"",
    "\"name\"",
    "<P_KEY>",
    "<STRING_LITERAL>",
    "<TERM>",
    "<NON_TERM>",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
  };

}
