/* Generated By:JJTree: Do not edit this line. ./QueryParserTreeConstants.java */

package org.apache.oodt.cas.catalog.query.parser;

public interface QueryParserTreeConstants
{
  int JJTPARSEINPUT = 0;
  int JJTQUERY = 1;
  int JJTQUERYEXPRESSION = 2;
  int JJTSTDQUERYEXPRESSION = 3;
  int JJTCOMPARISONQUERYEXPRESSION = 4;
  int JJTPRIORITYQUERYEXPRESSION = 5;
  int JJTCUSTOMQUERYEXPRESSION = 6;
  int JJTGETVALUES = 7;
  int JJTGETPROPERTIES = 8;


  String[] jjtNodeName = {
    "parseInput",
    "Query",
    "QueryExpression",
    "StdQueryExpression",
    "ComparisonQueryExpression",
    "PriorityQueryExpression",
    "CustomQueryExpression",
    "getValues",
    "getProperties",
  };
}
