/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JJTree: Do not edit this line. ./QueryParserTreeConstants.java */

package gov.nasa.jpl.oodt.cas.catalog.query.parser;

public interface QueryParserTreeConstants
{
  public int JJTPARSEINPUT = 0;
  public int JJTQUERY = 1;
  public int JJTQUERYEXPRESSION = 2;
  public int JJTSTDQUERYEXPRESSION = 3;
  public int JJTCOMPARISONQUERYEXPRESSION = 4;
  public int JJTPRIORITYQUERYEXPRESSION = 5;
  public int JJTCUSTOMQUERYEXPRESSION = 6;
  public int JJTGETVALUES = 7;
  public int JJTGETPROPERTIES = 8;


  public String[] jjtNodeName = {
    "parseInput",
    "Query",
    "QueryExpression",
    "StdQueryExpression",
    "ComparisonQueryExpression",
    "PriorityQueryExpression",
    "CustomQueryExpression",
    "getValues",
    "getProperties",
  };
}
