#!/bin/sh
#/*
# * Licensed to the Apache Software Foundation (ASF) under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The ASF licenses this file to You under the Apache License, Version 2.0
# * (the "License"); you may not use this file except in compliance with
# * the License.  You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */

[ -f /etc/sysconfig/java ] && . /etc/sysconfig/java

CONF_HOME=.

for file in `find ${CONF_HOME}/lib/*.jar`; do
     LIB_DEPS="${file}:${LIB_DEPS}"
done

echo -n "Starting Configuration Publisher\n"
$JAVA_HOME/bin/java \
        	-cp ${LIB_DEPS} \
        	-Dlog4j.configurationFile=${CONF_HOME}/etc/log4j2.xml \
        	-Djava.ext.dirs=. \
            -Djava.util.logging.config.file=${CONF_HOME}/etc/logging.properties \
            -Dorg.apache.oodt.cas.cli.action.spring.config=${CONF_HOME}/policy/cmd-line-actions.xml \
            -Dorg.apache.oodt.cas.cli.option.spring.config=${CONF_HOME}/policy/cmd-line-options.xml \
        	org.apache.oodt.config.distributed.cli.ConfigPublisher "$@"
echo "OK"
sleep 1
exit 0
