/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package org.apache.oodt.cas.catalog.query.parser;

public interface QueryParserConstants {

  int EOF = 0;
  int SPACE = 4;
  int AND = 5;
  int OR = 6;
  int QUOTE = 7;
  int EQUALS = 8;
  int SEMI_COLON = 9;
  int COMMA = 10;
  int OPEN_BRACES = 11;
  int CLOSE_BRACES = 12;
  int OPEN_PARENS = 13;
  int CLOSE_PARENS = 14;
  int BUCKET_NAME_KEY = 15;
  int CUSTOM_NAME_KEY = 16;
  int P_KEY = 17;
  int EQ = 18;
  int GE = 19;
  int GT = 20;
  int LE = 21;
  int LT = 22;
  int TERM = 23;
  int VALUE = 24;
  int NON_TERM = 25;
  int STRING_LITERAL = 26;
  int SPECIAL_CHARS = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\" \"",
    "\" AND \"",
    "\" OR \"",
    "\"\\\'\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"bucketNames\"",
    "\"name\"",
    "<P_KEY>",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "<TERM>",
    "<VALUE>",
    "<NON_TERM>",
    "<STRING_LITERAL>",
    "<SPECIAL_CHARS>",
  };

}
