/* Generated By:JJTree: Do not edit this line. ./QueryParserTreeConstants.java */

package org.apache.oodt.cas.catalog.query.parser;

public interface QueryParserTreeConstants
{
  public int JJTPARSEINPUT = 0;
  public int JJTQUERY = 1;
  public int JJTQUERYEXPRESSION = 2;
  public int JJTSTDQUERYEXPRESSION = 3;
  public int JJTCOMPARISONQUERYEXPRESSION = 4;
  public int JJTPRIORITYQUERYEXPRESSION = 5;
  public int JJTCUSTOMQUERYEXPRESSION = 6;
  public int JJTGETVALUES = 7;
  public int JJTGETPROPERTIES = 8;


  public String[] jjtNodeName = {
    "parseInput",
    "Query",
    "QueryExpression",
    "StdQueryExpression",
    "ComparisonQueryExpression",
    "PriorityQueryExpression",
    "CustomQueryExpression",
    "getValues",
    "getProperties",
  };
}
