// Copyright 1999-2002 California Institute of Technology.  ALL RIGHTS RESERVED.
// U.S. Government Sponsorship acknowledged.
//
// $Id: ProductService.idl,v 1.1.1.1 2004-03-02 19:45:40 kelly Exp $

#include <Server.idl>

module jpl {
	module eda {
		module product {
			module corba {
				interface Server {
					typedef sequence <octet> RawData;
					exception ProductServiceException { string errorInfo; };
					RawData query(in RawData q) raises (ProductServiceException);
					RawData retrieveChunk(in string productID, in long long offset, in long length)
						raises (ProductServiceException);
					void close(in string productID) raises (ProductServiceException);
					oneway void destroy();
				};
				interface ProductService : ::jpl::eda::Server {
					Server createServer();
				};
			};
		};
	};
};
