// Copyright (c) 2001, California Institute of Technology.
// ALL RIGHTS RESERVED. U.S. Government sponsorship acknowledged.
//
// $Id: Server.idl,v 1.4 2004/03/11 15:50:08 kelly Exp $

module jpl {
	module eda {
		/** Enterprise server.
		 *
		 * All enterprise servers must extend this interface
		 * and implement this methods listed.
		 */
		interface Server {
			/** An array of bytes. */
			typedef sequence<octet> ByteArray;

                        /** Get the server's interface name.
                         *
                         * This describes the kind of the server.
                         *
                         * @return The server's interface name.
                         */
                        string getServerInterfaceName();

			/** Control the server.
			 *
			 * @param command Command to send to the server.
			 * @return Any results.
			 */
			ByteArray control(in ByteArray command);

			/** Asynchronously control the server.
			 *
			 * @param command Command to send to the server.
			 */
			oneway void controlAsync(in ByteArray command);
		};
	};
};