
CREATE TABLE CatalogServiceMapper (
  CAT_SERV_TRANS_ID VARCHAR2(255) NOT NULL ,
  CAT_SERV_TRANS_FACTORY VARCHAR2(255) NOT NULL ,
  CAT_TRANS_ID VARCHAR2(255) NOT NULL ,
  CAT_TRANS_FACTORY VARCHAR2(255) NOT NULL ,
  CAT_TRANS_DATE VARCHAR2(255) NOT NULL ,
  CATALOG_ID VARCHAR2(255) NOT NULL
);

CREATE INDEX CatalogServiceMapper_CSTId_idx ON CatalogServiceMapper(CAT_SERV_TRANS_ID);  
CREATE INDEX CatalogServiceMapper_CTId_idx ON CatalogServiceMapper(CAT_TRANS_ID);  
CREATE INDEX CatalogServiceMapper_CatId_idx ON CatalogServiceMapper(CATALOG_ID);  

EXIT;
