apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ${artifactId}-filemgr
  name: ${artifactId}-filemgr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ${artifactId}-filemgr
    spec:
      containers:
      - env:
        - name: SOLR_URL
          value: http://solr:8983
        image: ${artifactId}-filemgr:1.0-SNAPSHOT
        name: ${artifactId}-filemgr
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /oodt/filemgr/policy
          name: ${artifactId}-filemgr-policy
        - mountPath: /oodt/filemgr/logs
          name: ${artifactId}-logs
        - mountPath: /oodt/data
          name: ${artifactId}-data
        - mountPath: /tmp
          name: ${artifactId}-temp
      restartPolicy: Always
      volumes:
      - name: ${artifactId}-filemgr-policy
        persistentVolumeClaim:
          claimName: ${artifactId}-filemgr-policy
      - name: ${artifactId}-logs
        persistentVolumeClaim:
          claimName: ${artifactId}-logs
      - name: ${artifactId}-data
        persistentVolumeClaim:
          claimName: ${artifactId}-data
      - name: ${artifactId}-temp
        persistentVolumeClaim:
          claimName: ${artifactId}-temp
status: {}
