apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ${artifactId}-resmgr
  name: ${artifactId}-resmgr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ${artifactId}-resmgr
    spec:
      containers:
      - image: ${artifactId}-resmgr:1.0-SNAPSHOT
        name: ${artifactId}-resmgr
        ports:
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /oodt/resmgr/policy
          name: ${artifactId}-resmgr-policy
        - mountPath: /oodt/data
          name: ${artifactId}-data
        - mountPath: /oodt/resmgr/logs
          name: ${artifactId}-logs
        - mountPath: /tmp
          name: ${artifactId}-temp
      restartPolicy: Always
      volumes:
      - name: ${artifactId}-resmgr-policy
        persistentVolumeClaim:
          claimName: ${artifactId}-resmgr-policy
      - name: ${artifactId}-data
        persistentVolumeClaim:
          claimName: ${artifactId}-data
      - name: ${artifactId}-logs
        persistentVolumeClaim:
          claimName: ${artifactId}-logs
      - name: ${artifactId}-temp
        persistentVolumeClaim:
          claimName: ${artifactId}-temp
status: {}
