apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ${artifactId}-opsui
  name: ${artifactId}-opsui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ${artifactId}-opsui
    spec:
      containers:
      - env:
        - name: FILEMGR_URL
          value: http://filemgr:9000
        - name: GANGLIA_URL
        - name: RESMGR_URL
          value: http://resmgr:9001
        - name: WORKFLOW_URL
          value: http://workflow:9002
        image: ${artifactId}-opsui:1.0-SNAPSHOT
        name: ${artifactId}-opsui
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /oodt/workflow/policy
          name: ${artifactId}-workflow-policy
        - mountPath: /oodt/pcs/policy
          name: ${artifactId}-pcs-policy
      restartPolicy: Always
      volumes:
      - name: ${artifactId}-workflow-policy
        persistentVolumeClaim:
          claimName: ${artifactId}-workflow-policy
      - name: ${artifactId}-pcs-policy
        persistentVolumeClaim:
          claimName: ${artifactId}-pcs-policy
status: {}
