SET ECHO ON;
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD hh24:mi:ss';

CREATE TABLE PRODUCTS (
  PRODUCT_ID number(11) NOT NULL ,
  PRODUCT_STRUCTURE VARCHAR(20)  DEFAULT  ''NOT NULL, 
  PRODUCT_TYPE_ID number(11)  DEFAULT  '0'NOT NULL, 
  PRODUCT_NAME VARCHAR(255)  DEFAULT  ''NOT NULL, 
  PRODUCT_TRANSFER_STATUS VARCHAR(255) DEFAULT 'TRANSFERING' NOT NULL,
  PRIMARY KEY  (PRODUCT_ID)
);

CREATE INDEX PRODUCTS_idx ON PRODUCTS(product_id);  

EXIT;
