SET ECHO ON;
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD hh24:mi:ss';

CREATE TABLE PRODUCT_TYPES (
  PRODUCT_TYPE_ID number(11) NOT NULL ,
  PRODUCT_TYPE_NAME VARCHAR(255)  DEFAULT  ''NOT NULL, 
  PRODUCT_TYPE_DESCRIPTION VARCHAR(255)  DEFAULT  ''NOT NULL, 
  PRODUCT_TYPE_VERSIONER_CLASS VARCHAR(255) DEFAULT '',
  PRODUCT_TYPE_REPOSITORY_PATH VARCHAR(255)  DEFAULT  ''NOT NULL, 
  PRIMARY KEY  (PRODUCT_TYPE_ID)
);
 
CREATE INDEX PRODUCT_TYPES_IDX  ON  PRODUCT_TYPES(seqno);  

EXIT;
